### ISSUE TITLE
Wrong PHP version

### ISSUE THREAD

**Issue by mateMathieu** [YunoHost-Apps/invoiceninja5_ynh#59]
The PDF generator does not work on a freshly installed system.

```
$ sudo php /var/www/invoiceninja5/artisan optimize
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.32.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.32. in /var/www/invoiceninja5/vendor/composer/platform_check.php on line 24

```
Ynh is installed in a VM system.
It has its own domain, Let's encrypt certificate.

**Comment by rndmh3ro** [comment]
I transferred this issue from https://github.com/YunoHost-Apps/invoiceninja_ynh/ to here: https://github.com/YunoHost-Apps/invoiceninja5_ynh/

Then the error you pasted is expected since `php` uses 7.4. You have to run `php8.1`.
And even then does the error not indicate, that something's wrong. Can you describe the error more precisely? What's written in the log under `storage/logs/`? What's the error in the frontend?

**Comment by mateMathieu** [comment]
OK thank you for the transfer.
Sorry to reply so late.

I have made a clean install, it seems that we are having the same issues as #22
